# Generated by Django 5.2.8 on 2025-12-14 09:24

import apps.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Продукты", "Зарплата"', max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], help_text='Категория для доходов или расходов', max_length=10, verbose_name='Тип')),
                ('icon', models.CharField(help_text='Идентификатор иконки', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(help_text='Цвет в HEX формате (например: #EF4444)', max_length=7, validators=[apps.categories.models.validate_hex_color], verbose_name='Цвет')),
                ('is_system', models.BooleanField(default=False, help_text='Системные категории нельзя удалить', verbose_name='Системная категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='unique_category_name_type')],
            },
        ),
    ]
