# Generated by Django 5.2.8 on 2025-12-14 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название категории')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, validators=[django.core.validators.RegexValidator(message='Тип должен быть income или expense', regex='^(income|expense)$')], verbose_name='Тип')),
                ('color', models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в HEX формате (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет')),
                ('icon', models.CharField(default='category', help_text='Название иконки из Material Design Icons', max_length=50, verbose_name='Иконка')),
                ('is_default', models.BooleanField(default=False, help_text='Стандартные категории доступны всем пользователям', verbose_name='Стандартная категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('budget', models.ForeignKey(blank=True, help_text='Если NULL - стандартная категория', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budgets.budget', verbose_name='Бюджет')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['income', 'expense'])), name='cat_valid_type'), models.UniqueConstraint(condition=models.Q(('budget__isnull', False)), fields=('name', 'budget'), name='unique_cat_per_budget'), models.UniqueConstraint(condition=models.Q(('budget__isnull', True), ('is_default', True)), fields=('name',), name='unique_default_cat')],
            },
        ),
    ]
