# Generated by Django 5.2.8 on 2025-12-14 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('success', 'Успех'), ('error', 'Ошибка')], default='info', max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип связанного объекта')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_user_read')],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['info', 'warning', 'success', 'error'])), name='notif_valid_type')],
            },
        ),
    ]
