# Generated by Django 5.2.8 on 2025-12-14 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма транзакции', max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, help_text='Опциональное описание транзакции', verbose_name='Описание')),
                ('date', models.DateField(help_text='Дата когда произошла транзакция', verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budget', verbose_name='Бюджет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['budget', '-date'], name='transaction_budget__86a27c_idx'), models.Index(fields=['budget', 'category'], name='transaction_budget__03ebac_idx'), models.Index(fields=['type'], name='transaction_type_dae97e_idx'), models.Index(fields=['date'], name='transaction_date_ad8c94_idx')],
            },
        ),
    ]
