# Generated by Django 5.2.8 on 2025-12-14 18:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('categories', '0002_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, validators=[django.core.validators.RegexValidator(message='Тип должен быть income или expense', regex='^(income|expense)$')], verbose_name='Тип транзакции')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budget', verbose_name='Бюджет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['budget', '-date'], name='idx_budget_date'), models.Index(fields=['budget', 'category'], name='idx_budget_category'), models.Index(fields=['type'], name='idx_trans_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='trans_amount_positive'), models.CheckConstraint(condition=models.Q(('type__in', ['income', 'expense'])), name='trans_valid_type')],
            },
        ),
    ]
