# Generated by Django 5.2.8 on 2025-12-14 18:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Текущая сумма')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='budgets.budget', verbose_name='Бюджет')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_goals', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'constraints': [models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='goal_target_amount_positive'), models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='goal_current_amount_non_negative'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed', 'cancelled'])), name='goal_valid_status')],
            },
        ),
    ]
