# Generated by Django 5.2.8 on 2025-12-14 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Мой бюджет", "Семейный бюджет"', max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('personal', 'Личный'), ('family', 'Семейный')], default='personal', help_text='Личный или семейный бюджет', max_length=10, verbose_name='Тип бюджета')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль (₽)'), ('USD', 'Доллар США ($)'), ('EUR', 'Евро (€)')], default='RUB', help_text='Валюта по умолчанию для транзакций', max_length=3, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(help_text='Пользователь, создавший бюджет', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
