# Generated by Django 5.2.8 on 2025-12-14 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название бюджета')),
                ('type', models.CharField(choices=[('personal', 'Личный'), ('family', 'Семейный')], default='personal', max_length=20, validators=[django.core.validators.RegexValidator(message='Тип должен быть personal или family', regex='^(personal|family)$')], verbose_name='Тип бюджета')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('KZT', 'Тенге')], default='RUB', max_length=3, validators=[django.core.validators.RegexValidator(message='Валюта должна быть RUB, USD, EUR или KZT', regex='^(RUB|USD|EUR|KZT)$')], verbose_name='Валюта бюджета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
            },
        ),
        migrations.CreateModel(
            name='BudgetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='budgets.budget', verbose_name='Бюджет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник бюджета',
                'verbose_name_plural': 'Участники бюджетов',
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['personal', 'family'])), name='budget_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['RUB', 'USD', 'EUR', 'KZT'])), name='budget_valid_curr'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_budget_name'),
        ),
        migrations.AddConstraint(
            model_name='budgetmember',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'editor', 'viewer'])), name='bm_valid_role'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetmember',
            unique_together={('budget', 'user')},
        ),
    ]
