# Generated by Django 5.2.8 on 2025-12-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
    ]
